### PR TITLE
Support Acquia CLI

### LINKED ISSUE #66: Autocompletion not working with Acquia CLI
I'd like to enable autocompletion for [Acquia CLI](https://github.com/acquia/cli), which is a Symfony Console app. On my local setup, autocompletion works for other Symfony Console apps (i.e. Composer) but not Acquia CLI. Is some specific action required to enable integration?

If I run `symfony-autocomplete acli` it seems to dump the autocompletion file as expected, but simply running `acli [TAB]` produces no results, while `composer [TAB]` does.

### PR DESCRIPTION
**Pull request by danepowell**
Fix #66

Follows examples of #45 and #49

### CODE REVIEW

**Comment by ktomk** [comment]
> I actually think it should be second on the list since console is the canonical entrypoint, and everything else on the list is secondary.

Well spotted, very good thinking. 

> We should probably have a follow-up PR to alphabetize that list, and also alphabetize and add links to the support tools list in the README.

If you already have something of that prepared, you can also add another commit to this PR. Right now the acli link looks a bit alone in that list.

**Comment by ktomk** [comment]
The Github CI build also was stale so it didn't properly run. I've updated master, just in case for the next update, if you refresh on top of master, it should show recovered. Sorry I didn't see this earlier.

**Comment by danepowell** [comment]
I adjusted the wording of the README

**Comment by ktomk** [comment]
Just seeing the list in the README isn't alphabetized fully, I guess because of console as first entry, but in the readme its composer.

And I could start the build now and it shows its red. Please let me know if I can be of help. I might also be able to take a closer look later.

**Comment by danepowell** [comment]
I removed whitespace from the test fixture, I'm hoping that fixes tests. Otherwise I don't know what's going on.

**Pull request merged**
